### ISSUE TITLE
DO U SKIDDED THIS CODE!

### ISSUE THREAD

**Issue by sixgodcode** [peke5005/fepenis#10]
THIS CODE WAS MADE BY LORDMAMADA2!

**Comment by GRIPPERTV** [comment]
Dude I know where you live

**Comment by peke5005** [comment]
No! Its original code made by me, you can search it on github. lordmamada2 actually made a Penis script but it was only client. this one is FE and replicates on server. you can close this when you're done

**Comment by sixgodcode** [comment]
...

**Comment by sixgodcode** [comment]
FUCK.
