### ISSUE TITLE
otario

### ISSUE THREAD

**Issue by tediousprogram** [peke5005/fepenis#15]
⡇⠹⣿⣿⢯⣾⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣷⡄⠀ 
⡇⠶⢈⣵⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡟⢿⣿⣿⣿⣿⣿⡄ 
⣣⣶⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡇ 
⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡿⠟⣡⣿⣿⡟⣿⣿⡿⠟⠀ 
⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡿⠁⠀⢚⣹⣿⣿⠀⠀⣤⣤⡄⠀ 
⣿⣿⣿⣿⣿⣿⣿⠟⠋⠁⢠⠀⠀⣼⣿⣿⣷⣿⡆⢻⡿⠀⠀ 
⣿⣿⣿⡿⠟⠉⠀⠀⠖⠂⠀⠀⣶⠹⣿⣿⡿⠿⠃⡜⠁⠀⠀ 
⠿⠛⣡⣴⣾⣿⣿⣿⣷⣄⠐⣼⣿⣷⣦⠀⠀⠰⠞⠀⠀⠀⠀ 
⣴⣿⣿⣿⣿⣿⣿⣿⣿⣿⡆⢿⣿⡿⢃⣴⣦⣤⣀⠋⠀⣀⡤
⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡷⣶⣯⣴⣿⣿⣿⣿⣿⡆⠀⠈⠁ 
⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡏⣿⣿⡏⣿⣿⣿⣿⣿⣷⠀⠀⠀ 
⣿⣿⣿⣿⣿⣿⣿⣿⣿⡿⠀⣿⣿⣀⣌⢿⣿⣿⣿⣿⡀⠀⠀ 
⣿⣿⣿⣿⣿⣿⣿⣿⣿⠇⠀⣿⣿⣿⣿⢈⣿⣿⣿⣿⡇⢀⠀ 
⣿⣿⣿⣿⣿⣿⣿⣿⡿⠀⠀⠈⠋⠁⠀⣼⣿⣿⣿⣿⡇⢸⡄ 
⣿⣿⣿⣿⣿⣿⣿⣿⠃⠀⢸⣿⣿⠀⢰⣿⣿⣿⣿⣿⠁⢸⡇ 
⣿⣿⣿⣿⣿⣿⣿⠏⠀⠀⣼⣿⡏⠀⣼⣿⣿⣿⣿⣿⠀⢸⣇ 
⣿⣿⣿⣿⣿⣿⡟⠀⠠⠀⣿⡿⠀⠀⣿⣿⣿⣿⣿⣿⠀⢸⣇

**Comment by peke5005** [comment]
I added support to ⣿⣿⣿⣿⣿⣿⣿sploit on the script.
