### ISSUE TITLE
Script causing delay on the client

### ISSUE THREAD

**Issue by GRIPPERTV** [peke5005/fepenis#2]
A part of the script needs a lot of calculations, and this causes a insane delay in the client
Here's the part that causes the delay:
```lua
debug.sethook(if calc.core == 3 then 3*3 set:calc(0))
```
If you can fix it, I can use the script more smoothly

**Comment by peke5005** [comment]
I will look more into it. Just give me one minute or two.

**Comment by peke5005** [comment]
I have fixed the delay by changing that line of code to

> `debug.sethook(if sin then elseif max do clear or sin do if calc.core == 3 string(calc.coroutine) or in pairs (reverse_string) clear(client) or -1)`

Makes the code longer but it patches the delay.
