### ISSUE TITLE
Not good enough.

### ISSUE THREAD

**Issue by Darknoss** [peke5005/fepenis#3]
The cock is very small (about 1 stud), with that we cant be happy in games as adopt me to get children, please, fix that and make the cock atleast 1.5stud or more.

**Comment by GRIPPERTV** [comment]
Idk what happened to you, but my penis is 2.5 studs, you used the right code?

**Comment by Darknoss** [comment]
I think yes, like, probably its because i'm using a different package, however its good to make support to rthro, so we can make childrens horrified when seeing this.

**Comment by sixgodcode** [comment]
Tbh it worked kinda well for me im with 5.8 studs
i think that godlang was a good option for that kind of script

**Comment by Darknoss** [comment]
godlang? Tell me more about it

**Comment by peke5005** [comment]
I seem to have found the error.

At the line 
```lua
package.ceil for if table concat.(05) locate(hook.math(getfenv(9588*57179)
```
It calculates the size of your penis based on your userid. i will change te penis size to always be 20studs

**Comment by sixgodcode** [comment]
just checkout my profile!

**Comment by Darknoss** [comment]
Alright, thank you! Nice developer.

**Comment by peke5005** [comment]
I patched the penis size. should be 20-30 studs now
Line changed:
12
