### ISSUE TITLE
Not Scripted in the right Language!

### ISSUE THREAD

**Issue by sixgodcode** [peke5005/fepenis#4]
Probably the GodLang its a good option for this kind of Script!

**Comment by peke5005** [comment]
Hmmm, maybe i will do that. can you please send me the link for Godlang

**Comment by sixgodcode** [comment]
just checkout my profile!

**Comment by peke5005** [comment]
Thank you, i will close this when im ready to change to godlang

**Comment by tediousprogram** [comment]
worse than my name

**Comment by tediousprogram** [comment]
: تحذير: Fagot Detector V0.1 (Alpha): تحذير:

: no_entry: تم اكتشاف Fagot: no_entry:

@ 🎈 السماء 天 🖤 # 0001
: rotating_light: مستوى Fagot: +10/10: rotating_light:

: rotating_light: ابتعد عن المثليين ، إنه معدي. : rotating_light:

**Comment by peke5005** [comment]
I have just tried using godlang on my script. it was very laggy and took about 3 seconds to execute. while my script takes about half a second. Sorry i will keep lua
