### ISSUE TITLE
Crashing on RC7

### ISSUE THREAD

**Issue by Darknoss** [peke5005/fepenis#5]
I'm trying to execute this code on RC7 Level-8 and isnt running, can you add support to it? 

I dont know if it is a problem of my computer.

- GTX 1080 TI
- NiggaOS
- 8GB Ram

**Comment by sixgodcode** [comment]
To solve this problem just type in your NiggarMinal

os/niggachange.sdkosd --replace nigga/perm -ins niggadog

**Comment by peke5005** [comment]
You can go with six's fix
but i will add RC7 support!

**Comment by Darknoss** [comment]
I Tried that and now my niggaos has turned into WhiteOs, wtf

**Comment by peke5005** [comment]
I added RC7 Support now. should be working!
