### ISSUE TITLE
MY MOTHER SAW THE SCRIPT

### ISSUE THREAD

**Issue by GRIPPERTV** [peke5005/fepenis#6]
OH MY GOD, MY MOM SAW THE FUCKING PENIS, PLEASE CREATE A GUI TO CREATE/REMOVE THE PENIS AT ANY TIME, I DON'T WANT TO GO THROUGH THAT AGAIN

**Comment by peke5005** [comment]
Ok i will add a button to remove penis.

**Comment by Darknoss** [comment]
Delete your System32 folder, it should add a UI to delete it probably.

**Comment by peke5005** [comment]
You can press "E" now to disable the penis instantly.
If you press it too quickly it may break penis.
