### ISSUE TITLE
The code its not working well

### ISSUE THREAD

**Issue by sixgodcode** [peke5005/fepenis#9]
Pls fix it.

**Comment by GRIPPERTV** [comment]
Shut up, you is retarded

**Comment by peke5005** [comment]
Hello six. What problems are you having with the script?
Lag? not working? support fail? please tell me.

**Comment by sixgodcode** [comment]
Cock fail.

**Comment by peke5005** [comment]
Oh, try to press E when you execute the script, or change the value 
```lua
 local dfd = 5051
```
Change that value to 5050 or 5052 if you are using synapse crack.
